<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="CNHQ-07075929N" ignored="0" name="相关测试报告生成" tests="4" failures="3" timestamp="22 十月 2018 12:42:04 GMT" time="0.063" errors="0">
  <testcase name="test1" time="0.012" classname="com.course.extent.demo.TestDemoMethods">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at com.course.extent.demo.TestDemoMethods.test1(TestDemoMethods.java:11)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="test2" time="0.002" classname="com.course.extent.demo.TestDemoMethods"/>
  <testcase name="test3" time="0.001" classname="com.course.extent.demo.TestDemoMethods">
    <failure type="java.lang.AssertionError" message="expected [bb] but found [aa]">
      <![CDATA[java.lang.AssertionError: expected [bb] but found [aa]
at com.course.extent.demo.TestDemoMethods.test3(TestDemoMethods.java:21)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase name="logDemo" time="0.003" classname="com.course.extent.demo.TestDemoMethods">
    <failure type="java.lang.RuntimeException" message="程序运行时抛出的异常">
      <![CDATA[java.lang.RuntimeException: 程序运行时抛出的异常
at com.course.extent.demo.TestDemoMethods.logDemo(TestDemoMethods.java:28)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- logDemo -->
</testsuite> <!-- 相关测试报告生成 -->
